### ISSUE TITLE
The link of " id and features of Unsplash dataset" is invalid

### ISSUE THREAD

**Issue by caoyuanbao** [haofanwang/natural-language-joint-query-search#1]
In "Download the pre-extracted image id and features of Unsplash dataset, and put them under unsplash-dataset dir, details can be found in natural-language-image-search project.", the link of " id and features of Unsplash dataset" is invalid.

**Comment by haofanwang** [comment]
@caoyuanbao Thanks for your reminder, I have updated the link.

**Comment by weihao20** [comment]
The link is invalid again

**Comment by caoyuanbao** [comment]
自动回复：你好，我已经收到你的邮件，待我细看后联系曹洁
